language: c
install:
- wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
- wget https://raw.githubusercontent.com/dinosaure/ocaml-travisci-skeleton/master/.travis-docgen.sh
script: bash -ex .travis-opam.sh && bash -ex .travis-docgen.sh
sudo: true
env:
  matrix:
  - PACKAGE="validator" OCAML_VERSION=4.02 PINS="mrmime:https://github.com/oklm-wsh/MrMime.git"
  global:
  - secure: cb/e0jKk7Zn4ZKTLEbNn+HzpAGNMa3IBF0sLCjnqGlxmT6O9OLlR7CcKK803NddhDeGI7YYbwp4UsLUvwOdS2GFyvOrh4O/z9jGN7hDaHGbGInFZrpctDpZPfKrYQmP/L4+RYtKpTRMoQK9o0tDST7mVpZnZtrwj6X1pCLsvAbKKFMrZ65VOrqRWwbLnXewbWidRrMgLCQVA3cEFAI+r6ZzzxyeZDl5Pu8+FUK06DJQ9vV/qcDl/QgG+t0g8AYpR7QJGPjOrpRRkQQZ2kY4oJj10SySL4BXxW91IB7DfhDmkR/Hqq12gyBKD6KKnVmL1tZpa6qsuH2Um8Pd0vAkS/KIJqlwq0Ve+74RxPNb2mkfy9ZUXXPrcuMF1B5HP90BuaglmNWtEffu19KNchYP97jSyIyfxX10d+InVw9vAMIrZn4lTrUaMVRIxjv/y3awiVekVbPEhtss1yo0j7Ps1Mwp/PESnIlgTC6zs92KcTy3GfjpUfYwos8sbUP4VdAtefRfNqiTeAbqTN8tFNxqNs6M+aYBtKQ/haIXlR28guE3NsDgQZTgMJyUNMi0+IhHV8Zf0uhQLFl/qxFYzFanoYXDGq/n6mevvybfHwlndPnQkjcXMMNr1QrYLXvmbP7MzM8aI9C2ch12vh1wtQrYc6UGuvGQlbNCZPT+2oZfGQlU=
